[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
overflow-checks = true
incremental = true

[workspace]
members = [
    "client",
    "object_perf",
    "server",
    "util",
    "zcdb",
    "zettacache",
    "zettaobject",
    "zoa",
]
